language: android
dist: trusty
android:
  components:
    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

script:
  - ./gradlew clean build

# deploy section
deploy:
  provider: script
  script: ./gradlew bintrayUpload
  on:
    branch: master